### PR TITLE
Improvements and fixes

### PR DESCRIPTION
**Pull request by Mesenotaur**
@TalkLounge This Pull Request adds (almost) all the changes I made in my fork of counter:
- It fixes a crash making counter never work with newer Minetest versions (thanks to Miniontoby on the forums!).
- It fixes grammatical mistakes in the formspec and also shortens the text there just a little.
- It adds a little bit more detailed description (maybe you could also copy my new and detailed repo description and add it?).
- It changes the version to 1.4.

I hope you appreciate it and will merge my PR; thanks.

### CODE REVIEW

**Comment by TalkLounge** [comment]
Do these changes work for both Minetest Versions, 5.x and 0.4.x on public servers and singleplayer? Have you tested it?

Thanks for your effort!

**Comment by Mesenotaur** [comment]
Hey there, thanks for the quick answer.
I didn’t test everything yet. My fork works perfectly in Minetest 5.4.1 on a server; in singleplayer, it works well for the session you play, but when you disconnect and reconnect from the world, it forgets everything.
Testing Minetest 0.4.17.1 (through WINE on Linux) showed that the mod works works the same in singleplayer as in 5.4.1. But maybe this is a problem with WINE. On a server (Wildes Land 2 :) ) it remembered everything on every reconnect.
Was this behavior the same with your original mod? So does only the server remember?
Shall I also test the current of your mod?

**Comment by TalkLounge** [comment]
Sorry for the late reply
It is merged now
Additionally I will change the code to make it work on singleplayer and servers on both versions

**Comment by Mesenotaur** [comment]
@TalkLounge Great! :D
I'm happy to have helped.

**Pull request merged**
